apiVersion: v1
kind: DeploymentConfig
metadata:
  name: app-deployment
  annotations:
    prometheus.io/path: /actuator/prometheus
    prometheus.io/port: "8080"
    prometheus.io/scrape: "true"
spec:
  replicas: 1
  selector:
    name: app-deployment
  strategy:
    type: Rolling
    rollingParams:
  template:
    metadata:
      annotations:
        prometheus.io/path: /actuator/prometheus
        prometheus.io/port: "8080"
        prometheus.io/scrape: "true"
      labels:
        name: app-deployment
    spec:
      containers:
      - image: "172.30.1.1:5000/test/application-image:latest"
        imagePullPolicy: IfNotPresent
        name: application 
        readinessProbe:
          httpGet:
            path: /
            port: 8080
            scheme: HTTP
  triggers:
  - type: ConfigChange

