apiVersion: v1
kind: Service
metadata:
  name: application   
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/actuator/prometheus"
    prometheus.io/scheme: http
    prometheus.io/port: "8080"
spec:
  selector:                  
    name: app-deployment
  ports:
  - nodePort: 0
    port: 8080               
    protocol: TCP
    targetPort: 8080
