kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "sunrise-pipeline"
spec:
  source:
    contextDir: "complete"
    git:
      uri: https://github.com/fluescher/gs-spring-boot.git 
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfilePath: "Jenkinsfile"
    type: JenkinsPipeline
  contextDir: "complete"
