node('maven') {
  stage('build') {
    sh "mvn clean package"
    stash name:"binary", includes:"target/gs-spring-boot-0.1.0.jar"
  }

  parallel {
    stage('Integration Tests') {
      sh "echo TESTING"
    },
    stage('UI-Tests') {
      sh "oc status"
    }
  }
  stage('deploy') {
    sh "sleep 60"
  }
}
